# Use the official ASP.NET Core runtime as the base image
# Stage 1: Build the application
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet publish -c Release -o /app

# Stage 2: Run the application
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app .
COPY ./Images ./Images
EXPOSE 80
ENTRYPOINT ["dotnet", "NZWalks.Api.dll"]



