// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZWalks.Api.Data;

#nullable disable

namespace NZWalks.Api.Migrations
{
    [DbContext(typeof(NZWalksDbContext))]
    [Migration("20241101161856_AddDifficultySeedData")]
    partial class AddDifficultySeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NZWalks.Api.Models.DomainModels.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1ad5baba-b6e0-4bba-8c26-1b87ebb681dd"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("efafab3a-cf95-4d84-b92d-4fea45c16825"),
                            Name = "Hard"
                        },
                        new
                        {
                            Id = new Guid("3830149f-ec80-49fd-a483-9a7b4ac9dad8"),
                            Name = "Medium"
                        });
                });

            modelBuilder.Entity("NZWalks.Api.Models.DomainModels.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("62e43591-0a93-41fc-8d64-6f2e36d52749"),
                            Code = "AKL",
                            Name = "AuckLand",
                            RegionImageUrl = "https://media.timeout.com/images/105906099/1024/768/image.webp"
                        },
                        new
                        {
                            Id = new Guid("9b42912c-52a0-4db3-94a4-ad3e29a9f398"),
                            Code = "WEL",
                            Name = "Wellington",
                            RegionImageUrl = "https://www.nzherald.co.nz/resizer/v2/U3PYFRGZPBGDVPPDW2BV7WTZKM.JPG?auth=9b4a0d1de59f22fbfd9e75df13c9d639fc8ae68c391bdc63857e7518b33b659a&width=1440&height=810&quality=70&focal=922%2C451&smart=false"
                        },
                        new
                        {
                            Id = new Guid("9b42912c-52a0-4db3-94a4-ad3e29a9f339"),
                            Code = "HML",
                            Name = "Hamilton",
                            RegionImageUrl = "https://as2.ftcdn.net/v2/jpg/04/08/89/99/1000_F_408899914_F5UU2RTDtM3ZlxSKqc1PNLOJ87v2dr8i.jpg"
                        });
                });

            modelBuilder.Entity("NZWalks.Api.Models.DomainModels.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LenghtInkm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("regionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("regionId");

                    b.ToTable("walks");
                });

            modelBuilder.Entity("NZWalks.Api.Models.DomainModels.Walk", b =>
                {
                    b.HasOne("NZWalks.Api.Models.DomainModels.Difficulty", "difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NZWalks.Api.Models.DomainModels.Region", "region")
                        .WithMany()
                        .HasForeignKey("regionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("difficulty");

                    b.Navigation("region");
                });
#pragma warning restore 612, 618
        }
    }
}
